"""
Test configuration file containing datasets and metrics definitions
"""

DATASETS = [
    "banknote_authentication",
    "birds_bones_and_living_habits", 
    "blood_transfusion_service_center",
    "boston",
    "breast_cancer_coimbra",
    "breast_cancer_wisconsin_original",
    "breast_cancer_wisconsin_prognostic",
    "breast_tissue",
    "cardiovascular_study",
    "cifar10",
    "classification_in_asteroseismology",
    "cnae9",
    "coil20",
    "credit_risk_classification",
    "crowdsourced_mapping",
    "customer_classification",
    "date_fruit",
    "dermatology",
    "diabetic_retinopathy_debrecen",
    "dry_bean",
    "durum_wheat_features",
    "echocardiogram",
    "ecoli",
    "epileptic_seizure_recognition",
    "extyaleb",
    "fashion_mnist",
    "fetal_health_classification",
    "flickr_material_database",
    "fraud_detection_bank",
    "glass_identification",
    "har",
    "harbermans_survival",
    "hate_speech",
    "heart_attack_analysis_prediction_dataset",
    "heart_disease",
    "hepatitis",
    "hiva",
    "htru2",
    "human_stress_detection",
    "image_segmentation",
    "imdb",
    "insurance_company_benchmark",
    "ionosphere",
    "iris",
    "labeled_faces_in_the_wild",
    "letter_recognition",
    "magic_gamma_telescope",
    "mammographic_mass",
    "microbes",
    "mnist64",
    "mobile_price_classification",
    "music_genre_classification",
    "olivetti_faces",
    "optical_recognition_of_handwritten_digits",
    "orbit_classification_for_prediction_nasa",
    "paris_housing_classification",
    "parkinsons",
    "patient_treatment_classification",
    "pen_based_recognition_of_handwritten_digits",
    "ph_recognition",
    "pima_indians_diabetes_database",
    "pistachio",
    "planning_relax",
    "predicting_pulsar_star",
    "pumpkin_seeds",
    "raisin",
    "rice_dataset_cammeo_and_osmancik",
    "rice_seed_gonen_jasmine",
    "secom",
    "seeds",
    "seismic_bumps",
    "sentiment_labeld_sentences",
    "siberian_weather_stats",
    "skillcraft1_master_table_dataset",
    "smoker_condition",
    "sms_spam_collection",
    "spambase",
    "spectf_heart",
    "statlog_german_credit",
    "statlog_image_segmentation",
    "street_view_house_numbers",
    "student_grade",
    "taiwanese_bankruptcy_prediction",
    "turkish_music_emotion",
    "user_knowledge_modeling",
    "water_quality",
    "weather",
    "website_phishing",
    "wilt",
    "wine",
    "wine_customer",
    "wine_quality",
    "wireless_indoor_localization",
    "world12d",
    "yeast",
    "zoo"
]

METRICS = [
    ("calinski_harabasz", {"adjusted": False}),
    ("calinski_harabasz", {"adjusted": True}),
    ("davies_bouldin", {"adjusted": False}),
    ("davies_bouldin", {"adjusted": True}),
    ("dunn", {"adjusted": False}),
    ("dunn", {"adjusted": True}),
    ("i_index", {"adjusted": False}),
    ("i_index", {"adjusted": True}),
    ("silhouette", {"adjusted": False}),
    ("silhouette", {"adjusted": True}),
    ("xie_beni", {"adjusted": False}),
    ("xie_beni", {"adjusted": True}),
]

# Subset for quick testing
SMALL_DATASETS = [
    "iris",
    "wine", 
    "seeds",
    "glass_identification",
    "ecoli"
]

CALINSKI_ONLY = [
    ("calinski_harabasz", {"adjusted": False}),
    ("calinski_harabasz", {"adjusted": True}),
]